events {}

http {
    server {
        listen 8090;

        # Rewrite /openapi/v2/* → /v2/*
        location ~ ^/openionapi/v2/(.*)$ {
            proxy_pass http://127.0.0.1:8081/v2/$1;
            proxy_set_header Host $host;
        }

        # Optional fallback
        location / {
            return 404;
        }
    }
}